name: Generate PDF with Pandoc

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Vérifier la présence de entrée.md
      run: |
        if [ ! -f entrée.md ]; then
          echo "Erreur : entrée.md est manquant !"
          exit 1
        fi

    - name: Installer Pandoc et LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended

    - name: Générer le PDF
      run: |
        mkdir -p output
        pandoc entrée.md -o output/output.pdf

    - name: Ajouter le PDF au dépôt
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/output.pdf
        git commit -m "Ajout du PDF généré"
        git push

    - name: Mettre à jour le README avec le lien vers le PDF
      run: |
        echo "# PDF Généré" > README.md
        echo "[Télécharger le PDF généré](output/output.pdf)" >> README.md
        git add README.md
        git commit -m "Mise à jour du README avec le lien vers le PDF"
        git push
