name: Generate PDF with Pandoc

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Vérifier la présence de input.md
      run: |
        if [ ! -f input.md ]; then
          echo "Erreur : input.md est manquant !"
          exit 1
        fi

    - name: Installer Pandoc et LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended

    - name: Générer le PDF
      run: |
        mkdir -p sortie
        pandoc input.md -o sortie/output.pdf

    - name: Télécharger le PDF généré
      uses: actions/upload-artifact@v3
      with:
        name: pdf-généré
        path: sortie/output.pdf
